### ISSUE TITLE
Don't really understand what the formula means

### ISSUE THREAD

**Issue by fenghuijian** [theislab/pseudodynamics#1]
Hi
Could you explain the biological implications of your formula？
du(s,t)/dt = diffusion term - drift term + growth term

**Comment by davidsebfischer** [comment]
Hi @fenghuijian! Did you check out the accompanying manuscript at https://www.ncbi.nlm.nih.gov/pubmed/30936567 already? We explained this in the results section and also in the supplement. Let me know if that does not help!
